artifact_location: /content/drive/MyDrive/ZamanPersonalUsage/vesselSegmentation/models/mlflow/627456749151728112
creation_time: 1696107463220
experiment_id: '627456749151728112'
last_update_time: 1696107463220
lifecycle_stage: active
name: Vessel segementaion
