artifact_uri: /content/drive/MyDrive/ZamanPersonalUsage/vesselSegmentation/models/mlflow/627456749151728112/cabe442abd594b539adcea949c8d2405/artifacts
end_time: 1696107469208
entry_point_name: ''
experiment_id: '627456749151728112'
lifecycle_stage: active
run_id: cabe442abd594b539adcea949c8d2405
run_name: bald-carp-401
run_uuid: cabe442abd594b539adcea949c8d2405
source_name: ''
source_type: 4
source_version: ''
start_time: 1696107463280
status: 3
tags: []
user_id: root
